# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 205ca1d53e6e623fd0d81543609a25d5655933662fe90797637662848cbd35941c54711dea3b23f4a3348122ee0fbcc955cd007cf9bd15b3dd10cf9ad079abe1

test:
  secret_key_base: af417dee006213e92fe9c365790cf5af61bd5ffa0df5cf083e6d3c5936cdb1821296f03a85911b6cbd0d7368cd04ba56f22086116e42837aa1d4550187b771c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
